bitrise #3

diff --git a/bitrise.yaml b/bitrise.yaml
--- a/bitrise.yaml
+++ b/bitrise.yaml
@@ -138,11 +138,47 @@ workflows:
                 
                 # write your script here
                 
+                export CLOUDSDK_CONFIG=/Users/vagrant/git/.config/
+                
+                curl -sSL https://sdk.cloud.google.com 17 > /tmp/gcl && sudo bash
+                /tmp/gcl --install-dir=/Users/vagrant/git/gcloud --disable-prompts
+                
+                
+                # or run a script from your repository, like:
+                
+                # bash ./path/to/script.sh
+                
+                # not just bash, e.g.:
+                
+                # ruby ./path/to/script.rb
+      - script@1:
+          inputs:
+            - content: >-
+                #!/usr/bin/env bash
+                
+                # fail if any commands fails
+                
+                set -e
+                
+                # make pipelines' return status equal the last command to exit with
+                a non-zero status, or zero if all commands exit successfully
+                
+                set -o pipefail
+                
+                # debug log
+                
+                set -x
+                
+                
+                # write your script here
+                
                 echo $GCLOUD_KEY > ./gcloud_key_file.json
                 
-                gcloud auth activate-service-account --key-file=gcloud_key_file.json
+                /Users/vagrant/git/gcloud/google-cloud-sdk/bin/gcloud auth
+                activate-service-account --key-file=gcloud_key_file.json
                 
-                gcloud --quiet config set project $FIREBASE_PROJECT_ID
+                /Users/vagrant/git/gcloud/google-cloud-sdk/bin/gcloud --quiet config
+                set project $FIREBASE_PROJECT_ID
                 
                 
                 # or run a script from your repository, like:
